# Default values for ingress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      real_ip_header CF-Connecting-IP;
  hosts:
    # subdomain definition
    # staging:      *.dev.justo.cloud
    # production:   *.justo.mx
    - host: ""
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: ""
          servicePort: 8080
