{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "django.labels" . | nindent 4 }}
spec:
  schedule: '{{ .Values.cronjob.schedule | default "* * * * *"}}'
  timeZone: '{{ .Values.cronjob.timeZone | default "Etc/UTC" }}'
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: {{ .Release.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
              args:
                - |
                {{- include "django.cronjobCommand" . | nindent 18 }}
              {{- include "django.envFrom" . | nindent 14 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
