{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "nodejs.labels" . | nindent 4 }}
type: Opaque
data:
  {{- /*
    Secrets to be managed by team leaders
  */}}
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace .Release.Name) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- range $key, $value := $secretData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  release_name: {{ .Release.Name | b64enc | quote }}
{{- end }}
