{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "django.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configmap.values }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end }}
{{- end }}